version: '3.8'

services:
  whatsapp-agent:
    build: .
    container_name: vexnet-whatsapp-agent
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - dynamodb-local
    restart: unless-stopped

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    restart: unless-stopped